CONFIG_ZTEST=y
CONFIG_SOF_BOOT_TEST_STANDALONE=y
CONFIG_LOG_BACKEND_ADSP_MTRACE=y
CONFIG_ZTEST_STACK_SIZE=4096
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_ISR_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=32768
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_ZTEST_THREAD_PRIORITY=0
CONFIG_MAIN_THREAD_PRIORITY=0
CONFIG_ZTEST_TEST_DELAY_MS=0
CONFIG_USERSPACE=n
CONFIG_LIBRARY_DEFAULT_MODULAR=n
CONFIG_COMP_TDFB=n
CONFIG_MY_TEST_SYMBOL=y
CONFIG_MATH_IIR_DF1=y
CONFIG_SQRT_FIXED=y
CONFIG_INTEL_MODULES=n
CONFIG_LIBRARY_MANAGER=n
CONFIG_LIBRARY_AUTH_SUPPORT=n
CONFIG_LLEXT=n
CONFIG_LLEXT_STORAGE_WRITABLE=n
CONFIG_LLEXT_EXPERIMENTAL=n
CONFIG_LLEXT_TYPE_ELF_RELOCATABLE=n
CONFIG_USERSPACE=n
CONFIG_SOF_USERSPACE_LL=n
CONFIG_SOF_USERSPACE_PROXY=n
CONFIG_DYNAMIC_THREAD=n
CONFIG_DYNAMIC_THREAD_ALLOC=n
CONFIG_COMP_RTNR_STUB=y
CONFIG_CORDIC_FIXED=y

# Audio Components for ZTests
CONFIG_COMP_LEVEL_MULTIPLIER=y
CONFIG_COMP_SRC=y
CONFIG_COMP_ASRC=y
CONFIG_COMP_TONE=y
CONFIG_COMP_MIXIN_MIXOUT=y
CONFIG_COMP_ARIA=y
CONFIG_COMP_MFCC=y
CONFIG_COMP_CROSSOVER=y
CONFIG_COMP_DCBLOCK=y
CONFIG_COMP_IIR=y
CONFIG_COMP_DRC=y
CONFIG_COMP_MULTIBAND_DRC=y
CONFIG_COMP_RTNR=n
CONFIG_COMP_SMART_AMP=n
CONFIG_COMP_TDFB=y
CONFIG_COMP_GOOGLE_RTC_AUDIO_PROCESSING=n
CONFIG_COMP_GOOGLE_CTC_AUDIO_PROCESSING=n
CONFIG_COMP_IGO_NR=n
CONFIG_COMP_NXP_EAP=n
CONFIG_COMP_TENSORFLOW=n
CONFIG_COMP_SOUND_DOSE=y
CONFIG_COMP_COPIER=y
# CONFIG_DTS_CODEC is not set
CONFIG_COMP_UP_DOWN_MIXER=y
CONFIG_COMP_STFT_PROCESS=y
CONFIG_COMP_VOLUME=y
CONFIG_MINIMAL_LIBC=n
CONFIG_PICOLIBC=y
CONFIG_PICOLIBC_IO_FLOAT=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_COMP_FIR=y

# Math ZTests
CONFIG_SOF_MATH_ZTEST=y
CONFIG_COMP_TDFB_ZTEST=y
CONFIG_INTEL_ADSP_MIC_PRIVACY=n
