/* SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright(c) 2026 Intel Corporation.
 *
 * EQ IIR passthrough config for 2 channels
 * Auto-generated by gen_ztest_blobs.m - do not edit.
 */

#ifndef ZTEST_BLOB_EQ_IIR_BLOB_H
#define ZTEST_BLOB_EQ_IIR_BLOB_H

#include <stdint.h>

static const uint32_t eq_iir_blob[23] = {
	0x34464f53, 0x00000000, 0x0000003c, 0x0301d001,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x0000003c, 0x00000002, 0x00000001, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000
};

#endif /* ZTEST_BLOB_EQ_IIR_BLOB_H */
