/* SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright(c) 2026 Intel Corporation.
 *
 * TDFB passthrough config for 2 channels
 * Auto-generated by gen_ztest_blobs.m - do not edit.
 */

#ifndef ZTEST_BLOB_TDFB_BLOB_H
#define ZTEST_BLOB_TDFB_BLOB_H

#include <stdint.h>

static const uint32_t tdfb_blob[34] = {
	0x34464f53, 0x00000000, 0x00000068, 0x0301d001,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000068, 0x00020002, 0x00000001, 0x00000001,
	0x001e0000, 0x00000000, 0x00000000, 0xffff0004,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00004000, 0x00000000, 0xffff0004, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00004000,
	0x00000000, 0x00010000, 0x00020001, 0x00000000,
	0x00000000, 0x00000000
};

#endif /* ZTEST_BLOB_TDFB_BLOB_H */
